matrixsqrt=function(A){
fit=matrixEigen(A)
d=fit$value
d1=d*0
d1[d>0]=1/d[d>0]
d=sqrt(d)
d1=sqrt(d1)
A=matrixMultiply(fit$vector,t(fit$vector)*d)
B=matrixMultiply(fit$vector,t(fit$vector)*d1)
C=list(w=A,wi=B,eigenfit=fit)
return(C)
}

inf.test=function(res.inf,LD,LD2,Theta,A,var.res=1){
if(is.matrix(A)==T){
Varinf=LD
Var2=LD2
V=Theta/var.res
AT=matrixMultiply(t(A),V)
P=V-matrixMultiply(t(AT),matrixMultiply(matrixGeneralizedInverse(matrixMultiply(AT,A)),AT))
u=sum(res.inf^2)/2
PVar2=matrixMultiply(P,Var2)
e=sum(diag(PVar2))/2
h=sum(diag(matrixMultiply(PVar2,PVar2)))/2
kappa=h/2/e
v=2*e^2/h
}
if(is.vector(A)==T){
A=c(A)
Var2=LD2
V=Theta/var.res
delta=1/sum(A*matrixVectorMultiply(V,A))
AAT=matrixMultiply(t(t(A)),t(A))/delta
P=V-matrixListProduct(list(V,AAT,V))
u=sum(res.inf^2)/2/var.res
PVar2=matrixMultiply(P,Var2)
e=sum(diag(PVar2))/2
h=sum(diag(matrixMultiply(PVar2,PVar2)))/2
kappa=h/2/e
v=2*e^2/h
}
if(is.null(A)==1){
Varinf=LD
Var2=LD2
V=Theta/var.res
u=sum(res.inf^2)/2/var.res
VVar2=LD
e=sum(diag(VVar2))/2
h=sum(diag(LD2))/2
kappa=h/2/e
v=2*e^2/h
}
pv=pchisq(u/kappa,v,lower.tail=F)
return(list(pv=pv,u=u,v=v,kappa=kappa,h=h))
}

eigen_cumsum=function(D,thres=1){
d=cumsum(D)/sum(D)
ind=which(d>=thres)
if(length(ind)>1){
K=ind[1]
}
if(length(ind)==1){
K=length(D)
}
return(K)
}

group.pip.filter=function(pip.summary,pip.thres.cred=0.95){
ind=which(pip.summary$cs>0)
if(length(ind)>0){
J=max(pip.summary$cs[ind])
pip.summary$cs.pip=pip.summary$variable_prob
for(i in 1:J){
indi=which(pip.summary$cs==i)
summaryi=pip.summary[indi,]
pip.cred=sum(summaryi$variable_prob)
pip.summary$cs.pip[indi]=pip.cred
}
ind.keep=which(pip.summary$cs.pip>=pip.thres.cred)
cs=pip.summary$cs
cs.pip=pip.summary$cs.pip
cs->cs[pip.summary$variable]
cs.pip->cs.pip[pip.summary$variable]
cs[which(cs==-1)]=0
}else{
ind.keep=NULL
cs=pip.summary$cs.pip*0
cs.pip=pip.summary$cs.pip*0
}
return(list(ind.keep=pip.summary$variable[ind.keep],cs=cs,cs.pip=cs.pip,result=pip.summary))
}

top_K_pip=function(susie_summary,top_K=1,pip.min.thres=0.01,xQTL.pip.thres=0.5){
ind=which(susie_summary$cs>0&susie_summary$variable_prob>=pip.min.thres)
if(length(ind)>0){
susie_summary=susie_summary[ind,]
J=max(susie_summary$cs)
index=c()
for(j in 1:J){
indj=which(susie_summary$cs==j)
g=susie_summary[indj,]
if(length(indj)<=top_K){
index=c(index,g$variable)
}
if(length(indj)>top_K){
index=c(index,g$variable[top_K_indices(g$variable_prob,k=top_K)])
}
}
}
if(length(ind)==0){
index=which(susie_summary$variable_prob>=xQTL.pip.thres)
}
return(index)
}

top_K_indices <- function(vec, k=1) {
return(order(vec, decreasing = TRUE)[1:k])
}
